# This is a basic workflow to help you get started with Actions

name: ks_auto

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  
  build:
   
    runs-on: ubuntu-latest

   
    steps:
   
      - uses: actions/checkout@v3
      
      - name: 'Working'
        env:
          zh1: ${{ secrets.zh1 }}
        run: python ks_auto.py
          
          

